### ISSUE TITLE
🎯[Front][Feat] Vue.js 모듈화 디렉토리 생성

### ISSUE THREAD

**Issue by EI-FIE** [OmokNoonE/OmokNoonE#104]
### 기능 요약 (Feature Summary)
Vue.js로 개발하기 위한 환경 구축

### 작업 내용 (Work Description)
디렉토리를 크게 Header, Section, Footer로 분류하고 해당 대분류된 디렉토리 내에서 필요에 따라 디렉토리를 생성함
npm run dev를 통해 실제 웹 브라우저에 창이 띄워지는 지 확인함

### 관련 이슈 (Related Issues)
차후 필요에 따라 추가적인 디렉토리 생성 가능

### 체크리스트 (Checklist)
- [x] 새로운 기능에 대한 코드 작성 완료
- [x] 테스트 완료
- [x] 문서화 완료
- [x] 리뷰 요청

**Comment by CJC0512** [comment]
확인하였습니다. 고생하셨습니다. :)

**Comment by jlee38266** [comment]
회원 내용 기록 완료 및 업로드 된 코드 확인했습니다. 모두 고생하셨습니다! . 👍👍👍👍👍
